### ISSUE TITLE
toBuffer does not accept hex?

### ISSUE THREAD

**Issue by Josema** [ethereumjs/ethereumjs-util#103]
Hi, I am trying to get an address from a hexadecimal private key (Generated via MyEtherWallet)

```js
import { privateToAddress, toBuffer} from 'ethereumjs-util'

const private_key = '4563d0a5e0d03cd7f791dd38af0076eaead06658c4b9c0dfbc960feec7e28296'
privateToAddress(toBuffer(private_key))
```

Error:
```
Uncaught RangeError: private key length is invalid
    at Object.exports.isBufferLength (assert.js:31)
    at Object.publicKeyCreate (index.js:61)
    at exports.privateToPublic (index.js:305)
    at exports.privateToAddress (index.js:423)
```

Using `new Buffer(private_key, 'hex')` instead it works. I don't see the point of using toBuffer if i can just import a string private key. What am I missing here?

**Comment by fanatid** [comment]
add `0x` to private key...
and check source code https://github.com/ethereumjs/ethereumjs-util/blob/926f2d742c9d9e7853ef226a67e6ecd9179409b2/index.js#L153-L175
