### ISSUE TITLE
5.1.3 should have been released as 5.2.0

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-util#117]
Basically 5.1.3 introduced ES6 feature and requires babel.

For example ethereum/solc-js was using `^5.1.2`, which allows downloading `5.1.3`, but wasn't prepared to handle ES6 and as a result builds on node 4 and 5 are failing: https://travis-ci.org/ethereum/solc-js/builds/337096439

@holgerd77 @Silur @jwasinger the org should be more careful with breaking changes :)

**Comment by holgerd77** [comment]
Yes, you're right. I think got deeper into this whole field of ``ES5``, ``ES6``, babel, transpilation and publishing in the last weeks, will also try to more keep an eye on this on future releases.

That said: is this really an issue or just a comment? Are you ok with publishing ``v5.1.4`` through https://github.com/ethereumjs/ethereumjs-util/pull/116 (and could you approve then?)?

This should also fix the ``solc-js`` build and put the ``5.1.x`` line back on track (Node 4 is also reincluded there for testing).

**Comment by axic** [comment]
Well it is an issue in the sense we have to peg to a version, but if you the next release actually fixes the problem then it should be in the 5.1.x line so that anyone using semver `^5.1.0` would be covered.

**Comment by holgerd77** [comment]
Fixed by https://github.com/ethereumjs/ethereumjs-util/pull/116
