### ISSUE TITLE
Test constants like KECCAK256_NULL_S

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-util#122]
Testing the constants like ``KECCAK256_NULL_S`` seems trivial, but there is always the risk of either an accidental character insertion/deletion while doing other stuff, or something breaking the export, which would also remain unnoticed.

So there should be some simple checks in the tests here.

**Comment by Neurone** [comment]
Adding more tests does not seems to me a solution. I think the best approach to avoid that unwanted changes goes unnoticed it is to separate constants from the main file, using i.e. a specific `constants.js`. This way there's no risk to change those constants while working on other stuff and it is _super easy_ to see when a constant is changed (so actually becoming a _variable_? 😄 )

**Comment by holgerd77** [comment]
"Solution" is a big words for tests 😄, I think this could prevent some issues (e.g. loosing the exports accidentally if someone adds ``exports = exports.newFunction(...)`` accidentally, stuff like that, this is no super-high-priority issue though.

Moving constants into its own file is somewhat separate from this I would say, wouldn't be against this on a first though, this would fit together with the changes from https://github.com/ethereumjs/ethereumjs-util/pull/38.
