### ISSUE TITLE
Remove setLength and sha3 in next breaking release

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-util#124]

**Comment by Anaphase** [comment]
Yeah, the docs say `sha3` is obsolete and 121b4d9 shows that `keccak` should be used in it's place. However, this change hasn't been published to npm yet ¯\\\_(ツ)_/¯. The docs should reflect what's currently published; might be time for 6.0.0?

**Comment by holgerd77** [comment]
@Anaphase Thanks for the reminder, have prepared a PR for a release on this: https://github.com/ethereumjs/ethereumjs-util/pull/127

**Comment by holgerd77** [comment]
Note on this: sha3 references has been removed in the ``v6.0.0`` release. A bit unfortunate, didn't remove ``setLength`` (see [here](https://github.com/ethereumjs/ethereumjs-util/blob/master/index.js#L106) in the code), this would still have to be done in the next major release.

I would interpret the change to be done as: ``setLength()`` has been replaced with ``setLengthLeft()`` at some point in time, the ``setLength()`` alias should be removed, please correct me if I am wrong.

**Comment by axic** [comment]
> I would interpret the change to be done as: setLength() has been replaced with setLengthLeft() at some point in time, the setLength() alias should be removed, please correct me if I am wrong.

Correct.

**Comment by axic** [comment]
`sha3` was removed in #154, but `setLength` is still in.

**Comment by holgerd77** [comment]
`setLength` has been removed in #244 and published along the [v7.0.0](https://github.com/ethereumjs/ethereumjs-util/releases/tag/v7.0.0) release, will close.
