### ISSUE TITLE
Make v 27 or 28

### ISSUE THREAD

**Issue by Firescar96** [ethereumjs/ethereumjs-util#131]
https://github.com/ethereumjs/ethereumjs-util/blob/54aa41ccb5c09de626ee358499e2efab535bc0bf/index.js#L410

To maintain consistency with go-ethereum v should be 27/28 instead of 0/1

**Comment by holgerd77** [comment]
Hi, thanks for reporting, could you provide a bit more context, maybe a link to the Go implementation and one to the Whitepapier or an explanation?

**Comment by holgerd77** [comment]
Sorry for coming back to this so late, I was a bit afraid of changing signature-related code. Now had a closer look, since both Geth and Parity did the change this seems to be safe.

Are you willing to do a PR on this? Promise to further keep track from now on.

**Comment by Firescar96** [comment]
sure

**Comment by holgerd77** [comment]
Cool, thanks!

**Comment by Neurone** [comment]
I proposed a fix for this issue.

**Comment by holgerd77** [comment]
Thanks for the PR, great!

@Firescar96 @Neurone For ``toRpcSig``: do you think it is really safe to completely switch to the ``27``/``28`` version or should we allow both by making exceptions for all four values like:

```javascript
if (v !== 0 && v !== 1 && v !== 27 && v !== 28) {
   throw new Error('Invalid recovery id')
}
```
...and then just pass the value like in the PR from Giuseppe? Are there/might there be still use cases for the ``0``/``1`` version? Don't really have a real-world feeling for that.

**Comment by holgerd77** [comment]
@Firescar96 @Neurone A bit similar question arises for the ``fromRpcSig`` method, but the other way around from a change-or-not-change point of view: this is currently [supporting both versions](https://github.com/ethereumjs/ethereumjs-util/blob/master/index.js#L442). Is it time to drop this or should we leave "as is"?

**Comment by holgerd77** [comment]
@Firescar96 @Neurone For [ecrecover](https://github.com/ethereumjs/ethereumjs-util/blob/master/index.js#L395) I would also propose to remove the ``v - 27`` and just pass the value through as a base line.

On top similar question: we could support both versions there and throw an error similar to the ``toRpcSig`` example I posted as code above. Or we could drop the old version.

**Comment by Neurone** [comment]
I think the best option is to comply with all other clients and use only `27/28`. About ecrecover in particular, you should NOT remove `v - 27 ` because that value is used by `secp256k1` library, that works with `0/1`, not `27/28`

**Comment by holgerd77** [comment]
@Neurone Oh yes, that makes sense (``ecrecover``), thanks! What is your stance on ``fromRpcSig``? Do you think it has benefits to drop the old-version support there? Or should this stay "as is" with accepting both versions?

**Comment by holgerd77** [comment]
@Neurone Your answer is a bit ambiguous: so would you support remove the old-version support from ``fromRcpSig`` (which I would read from your first paragraph) or be in favor of keeping it (second paragraph 😄 )?

**Comment by Neurone** [comment]
Keep the support while **reading old signatures** (it is already there, I created just now a test to demonstrate it and I added it to the pull request https://github.com/ethereumjs/ethereumjs-util/pull/139/commits/1ca1c950b8e5c5bf04fe70477e51cb5f8eec3bcc)

While **creating new signatures** I suggest to keep toRpcSign _as is_ (`v` is valid only if it is `27` or `28`)

**Comment by holgerd77** [comment]
Ok, great, thanks for the extensive and quick answers, since this is sensitive and widely used code I want to be sure on this.

@Firescar96 Can you read up on this and give an opinion on the current status quo (basically the PR @Neurone did)?

**Comment by Firescar96** [comment]
The commit fixes my issue.
>because that value is used by secp256k1 library, that works with 0/1, not 27/28
Could you put a link to where in the code that's enforced?

**Comment by Neurone** [comment]
@Firescar96 [here](https://github.com/cryptocoinjs/secp256k1-node/blob/master/src/ecdsa.cc#L132) you can see that valid recovery values are `0`,`1`,`2` and `3`.
Values `2` and `3` - and therefore `29` and `30` for Ethereum signatures - are so rare that happens only in specific cases, so when you generate a random key `0` and `1` can be considered the sole correct values.

If we want to be **really fully compliant** with [secp256k1-node](https://github.com/cryptocoinjs/secp256k1-node) library - but maybe it should be another issue/feature - we should allow more values in `ecrecover` like this:

```
  if (recovery < 0 || recovery > 3) {
    throw new Error('Invalid signature v value')
  }
```
and more values in `toRpcSig `like this:

```
  if (v < 27 || v > 30) {
    throw new Error('Invalid recovery id')
  }
```
and restrict `v` in `fromRpcSig` to values `0,1,2,3,27,28,29,30`.
