### ISSUE TITLE
not able to build master branch in travis.ci

### ISSUE THREAD

**Issue by ShreyaGoel08** [ethereumjs/ethereumjs-util#153]
@holgerd77 

I need to raise a pull request to support for chromeHeadless with --no-sandbox flag  in aarch64
but could not succeed as the master branch is unstable can you have a look at this.

**Comment by ossdev07** [comment]
Hi,

I am trying to run the package on Travis.ci but facing issues. https://travis-ci.com/ssps12/ethereumjs-util

Errors are coming in the coveralls and lint section.

Can you please help me with this.

**Comment by ShreyaGoel08** [comment]
Hi,

I am trying to run the package on Travis.ci but facing issues. https://travis-ci.com/ssps12/ethereumjs-util

Errors are coming in the coveralls and lint section.

Can you please help me with this.

**Comment by holgerd77** [comment]
Why do you need the ``master`` branch and are not just taking the latest release on npm?

**Comment by whymarrh** [comment]
@ShreyaGoel08 don't run the Coveralls tests in your CI as there are environment variables that are required for that to work that you wouldn't have access to in your builds. For the lint, can you reproduce the same error locally?

@holgerd77 I think this issue can close this in favour of more specific issue as they crop up.
