### ISSUE TITLE
Should pad/rpad truncate the input if it is longer?

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-util#17]
The name is a bit misleading as padding means extending, but not truncating.

At least the docs have been updated to reflect this behaviour, but the question remains: should it truncate?

**Comment by wanderer** [comment]
agreed this is a bit weird. Is there are better name for this? I think truncating or padding is used in a input validation in several places.

**Comment by kumavis** [comment]
i agree rename makes the most sense.  tried to find prior art on the naming conventions, `setLength` is all i could find.

**Comment by wanderer** [comment]
maybe `padOrCut` ? #bikeshedding

**Comment by axic** [comment]
Make note that we have `pad` (left/prefix padding) + `rpad` (right/suffix padding) when thinking about names.

Maybe they could be merged into one method as well with a parameter? In that case the behaviour of `rpad` seems to be the natural one, e.g.:
- `padOrCut('1234', 2) == padOrCut('1234', 2, false) == rpad('1234', 2)` 
- `padOrCut('1234', 2, true) == pad('1234', 2)`

As a name suggestion, if the above is taken into consideration, how about `ensureLength`? And the name perhaps could reflect the fact this operates only on hex strings.

**Comment by kumavis** [comment]
good point on Rpad + (L)pad
* `ensureLength`
* `setLength`
* `ensureHexLength`
* `setHexLength`

meh

**Comment by wanderer** [comment]
ok i just changed it to `setLength(Buffer, Length, direction)` Any objects to this naming/API?

**Comment by kumavis** [comment]
:+1:

**Comment by axic** [comment]
@wanderer I think it makes more sense to assume it is right padded by default based on the name. I know that left padding is probably more widely used at the moment in ethereumjs-vm.

**Comment by wanderer** [comment]
@axic im also left handed; therefore left should be default :P

**Comment by kumavis** [comment]
seems like it should be something like `setLength(Buffer:required, Length:required, isPadRight=false)`

**Comment by wanderer** [comment]
so I got curious to what other pad implementation default too, in Java and Python there are just two seperate function a left and right version. So I just added aliases  `rsetLength` for right and `lsetLength` for left. I think that makes code more readable. If i didn't know the API rsetLength would mean more to me than `setLength(Buffer, Buffer, true)`

**Comment by kumavis** [comment]
i would prefer `setLengthRight` and `setLengthLeft` :bike: :house_with_garden:

**Comment by wanderer** [comment]
@kumavis ok we now have `setLength` `setLengthR` `setLengthL`

**Comment by axic** [comment]
If you have `setLengthL` and `setLengthR`, then `setLength` could just be available also :)

:+1: @kumavis, I do prefer `setLengthLeft` and `setLengthRight` too

- `setLength(Buffer, Length, isPadLeft=false)`
- `setLengthLeft(Buffer, Length)`
- `setLengthRight(Buffer, Length)`
