### ISSUE TITLE
Reach full test coverage

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-util#18]
Create tests for:
- defineProperties
- printBA
- baToJSON

**Comment by wanderer** [comment]
defineProperties is something i'm not really satisfied with. It attach a Array of properties to an object with setters that perform validation. I think this should be pulled out to it own module or find a module to replace this function. 

* printBA - just prints an array of buffers, this is a debugging function... maybe we should move it to ethereumjs-testing

* baToJSON - Also created for debugging but it has production use cases, use definitely needs a test

**Comment by wanderer** [comment]
2b7bf630ed14eab0c12b9484fc610b58cdb13454 adds tests for baToJSON

**Comment by wanderer** [comment]
meeh i'm just scrapping `printBA` its pretty much worthless at this point

**Comment by axic** [comment]
`baToJSON` (it doesn't even return JSON, only if the input is an Array) seems so specific for `defineProperties`, shouldn't that be internal to it?

**Comment by wanderer** [comment]
I have used it for debugging and creating text dumps, so thats why its not internal.

**Comment by wanderer** [comment]
I'm looking at [json-schema](http://json-schema.org/) to replace the validation done by defineProps

**Comment by wanderer** [comment]
done! i ended up just writing test for defineFields
