### ISSUE TITLE
Replace crypto library (secp256k1->elliptic)

### ISSUE THREAD

**Issue by gurrpi** [ethereumjs/ethereumjs-util#184]
Currently `ethereumjs` uses [secp256k1](https://github.com/cryptocoinjs/secp256k1-node/) for crypto functionality(ECDSA sign, verify...and so on). But this library is incomplete as it could only verify **lower-s signature** (See also https://github.com/cryptocoinjs/secp256k1-node/issues/90).
 Therefore a function like `isValidSignature` would return false when input signature is **high-s** although it is a valid signature but unsupported by `secp256k1`. So I suggest using [`elliptic`](https://github.com/indutny/elliptic) that support full compatibility.

**Comment by s1na** [comment]
Do you know by any chance how the performance compares? Btw, do you have a valid input signature which would fail, so we can add a test case?

**Comment by fanatid** [comment]
@gurrpi why not use `signatureNormalize` (convert signature to lower-S) before validation?

@s1na elliptic very slow compare to bindings, you can check results for bindings/wasm/elliptic here: https://blog.bitjson.com/just-released-webassembly-version-of-secp256k1-10x-faster-than-javascript-eb3cebe4d411

**Comment by gurrpi** [comment]
@fanatid Thanks for informing benchmark.

Closing this issue since Ethereum also only accept low-s signature. 
[ref](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2.md)
