### ISSUE TITLE
GenerateAddress without hex-prefixed from

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-util#185]
I can't figure out why the generated address for a hex-prefixed `from` differs from that of a non-hex-prefixed `from`? My guess is that one of these test cases is invalid.

https://github.com/ethereumjs/ethereumjs-util/blob/8ffe697fafb33cefc7b7ec01c11e3a7da787fe0e/test/index.js#L419-L424

https://github.com/ethereumjs/ethereumjs-util/blob/8ffe697fafb33cefc7b7ec01c11e3a7da787fe0e/test/index.js#L426-L431

**Comment by alcuadrado** [comment]
In the first case, the string was being decoded as utf8. 

I updated this test in #197, making it more explicit.

**Comment by s1na** [comment]
Thanks, that clears it up.
