### ISSUE TITLE
Should publicToAddress support RFC5480 input?

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-util#19]
Having fixed a few bugs in `publicToAddress` it finally properly validates the input and as before it will allow:
- an uncompressed 64 byte encoded point (x,y)
- the uncompressed "RFC5480" encoding (type 4)

However I do not think it should support the RFC5480 encoding at all. Ethereum doesn't use it and when devs are using other crypto tools to interact with Ethereum they should be aware of the differences to avoid mistakes.

The relevant piece of code: https://github.com/ethereumjs/ethereumjs-util/blob/master/index.js#L301

See RFC5480 here: https://www.ietf.org/rfc/rfc5480.txt

>  The first octet of the OCTET STRING indicates whether the key is
        compressed or uncompressed.  The uncompressed form is indicated
        by 0x04 and the compressed form is indicated by either 0x02 or
        0x03 (see 2.3.3 in [SEC1]).  The public key MUST be rejected if
        any other value is included in the first octet.

SEC1 is here: http://www.secg.org/SEC1-Ver-1.0.pdf

**Comment by axic** [comment]
I think this becomes rather a generic question about the crypto API in `util`.

As Ethereum public keys (and subsequently the addresses) don't use the above type field, currently it is stripped in all occasions, one exception being publicToAddress accepting it as input.

I think it should be more consistent

**Comment by axic** [comment]
Based on the yellow paper (Appendix F), we can assume the pubkey is always an uncompressed one without the type flag.

> Where p_u is the public key, assumed to be a byte array of size 64 (formed from the concatenation of two positive integers each < 2^256) and p_r is the private key, a byte array of size 32 (or a single positive integer in the aforementioned range).

**Comment by wanderer** [comment]
What are the disadvantage of being able to parse both formats?

**Comment by axic** [comment]
For example one could think if a given public key works as an input to `publicToAddress`, a key generated from the same private key using `privateToPublic` should equal. And they wont as the latter gives back the Ethereum formatted pubkey.

**Comment by wanderer** [comment]
Cool ; so We came to a compromise to allow both types of encoding via an boolean options in #21
