### ISSUE TITLE
Use js-sha3 instead of keccak.

### ISSUE THREAD

**Issue by MicahZoltu** [ethereumjs/ethereumjs-util#195]
The `keccak` NPM package causes no end of problems due to its node-gyp requirement.  This library should switch to use `js-sha3` NPM package which is a native JS sha3 library that works in both browser and node and has no node-gyp dependency.

**Comment by pgebheim** [comment]
Agreed @MicahZoltu !

It would be great to remove the dep on ethereumjs-util and keccak and just use js-sha3 directly.

The Augur dev team has spent countless days on terrible issues with node-gyp re: sha3.

**Comment by MicahZoltu** [comment]
Note: It appears this library also has a dependency on `secp256k1`.  I am not sure if there is a native JS implementation of that or not, but it leads to the same problems as `keccak` does with regards to node-gyp dependency.

**Comment by MicahZoltu** [comment]
https://www.npmjs.com/package/elliptic is a JS-only implementation of various ECC functions, including `secp256k1`.

**Comment by fanatid** [comment]
@MicahZoltu is your issue related with node v12?

**Comment by MicahZoltu** [comment]
@fanatid `node v10.15.0`, `npm v6.4.1`.  It appears you are correct that it does fallback to JS, but during the `npm install` process I get giant ugly red NPM install failure error.  It took me a while to figure out the error wasn't critical/terminal.

Also note that I cannot use the fallbacks directly in my project like that since I'm getting `secp256k1` and `keccak` functionality transitive through `ethereumjs-util`.

**Comment by fanatid** [comment]
Can you paste error? I just checked `keccak` with `node v10.15.0` and building ok (only warning messages shown)

You completely right, that if libraries used not directly then bindings have precedence, there 2 ways for solving this:
1) add `ignore-scripts=true` to `.npmrc`
2) run something like `find node_modules/ -type d -regex ".*?/keccak/build$" -exec rm -rf {} \;` after installation (in this case JS fallback will be used)

**Comment by MicahZoltu** [comment]
I'm guessing your system has all of the necessary build tool prerequisites, which is often not the case on any given developer or CI machine.
```
PS C:\...\test> npm install ethereumjs-util

> keccak@1.4.0 install C:\...\test\node_modules\keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild C:\...\test\node_modules\keccak
> node-gyp rebuild


C:\...\test\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\...\test\node_modules\keccak
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\...\AppData\Local\npm\npmrc\_logs\2019-05-07T10_44_18_464Z-debug.log
"Keccak bindings compilation fail. Pure JS implementation will be used."

> secp256k1@3.6.2 install C:\...\test\node_modules\secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.6.2 rebuild C:\...\test\node_modules\secp256k1
> node-gyp rebuild


C:\...\test\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\...\test\node_modules\secp256k1
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.6.2 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.6.2 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\...\AppData\Local\npm\npmrc\_logs\2019-05-07T10_44_20_058Z-debug.log
"Secp256k1 bindings compilation fail. Pure JS implementation will be used."
npm WARN test No description
npm WARN test No repository field.
npm WARN test No license field.

+ ethereumjs-util@6.1.0
added 31 packages from 35 contributors and audited 165 packages in 6.096s
found 0 vulnerabilities
```

**Comment by holgerd77** [comment]
We would probably have to examine very carefully what the performance implications of such a switch would be. That said I'm very familiar (as a user within the other EthereumJS libraries) with the problems described. Didn't put much reflection in it yet though.

**Comment by fanatid** [comment]
Ah... windows. That's explain all :D
Small guide about this: https://github.com/cryptocoinjs/secp256k1-node#windows
From my small experience with Windows, it's enough install https://github.com/felixrieseberg/windows-build-tools

**Comment by MicahZoltu** [comment]
The purpose of this issue isn't to solve my specific problem, I already know how to do that.  It is to address the general problem that node-gyp causes great headache.  Windows isn't the only problem, node-gyp also causes problems on Linux when running in a constrained environment like trim docker images, build servers, etc.

Ideally the build tools required to build/test a node project are node and NPM.  Node-gyp based libraries require also installing a whole suite of additional tools just to install dependencies.

In the case of this library, dropping node-gyp requirement merely requires switching out a couple dependencies.  Since this project is used all over the ecosystem, such a change would have far reaching effects.

**Comment by alcuadrado** [comment]
I'm with @MicahZoltu here. Using native modules in public libraries is an error IMO. I can't tell how many hours I've lost compiling the same things over and over. It makes the Ethereum developer experience a little painful.

> We would probably have to examine very carefully what the performance implications of such a switch would be. That said I'm very familiar (as a user within the other EthereumJS libraries) with the problems described. Didn't put much reflection in it yet though.

One idea I've had in the back of my mind for a long time is that libraries should default to js implementations of everything, and make performance improvements via native module opt-in.

This could work by making the native modules optionalDependencies, and adding a thin layer of abstraction on top of the different implementations. Something like:

```js
let nativeKeccak;
let jsKeccak;

try {
  nativeKeccak = require("native-keccak")
} catch (error) {
  jsKeccak = require("js-keccak");
}

if (nativeKeccak !== undefined) {
   module.exports = (input) => {
     // maybe some code to adapt the input
     return nativeKeccak(input); // and maybe adapt the output
   }
} else {
   module.exports = (input) => {
     // maybe some code to adapt the input
     return jsKeccak(input); // and maybe adapt the output
   }
}
```

The advantage of this approach is that it doesn't use native modules by default, so no compiling. And that if you really need better performance, you can still use the native modules.

**Comment by pgebheim** [comment]
You don't even NEED to do anything special to get native keccack in a project that needs it.

just *dont depend on keccak*. Just grab the actual implementation you want.

As I said above, this particular library is *not useful* and everyone should be discouraged from using it -- it should NOT add more hacks to get people caught into this odd false choice.

**Comment by fanatid** [comment]
@alcuadrado both keccak/secp256k1 will not fail installation if building not work, you will see error messages yes, but exit code will be zero and pure js will be used in this case.
https://github.com/cryptocoinjs/keccak/blob/master/index.js
https://github.com/cryptocoinjs/secp256k1-node/blob/master/index.js

I agree that installation should be as much as easier, but have no idea how fix this, optionalDependencies is not fix.
@MicahZoltu with optionalDependencies you will see same error messages in logs and result will be same, ethereumjs-util will be installed.
```
+ ethereumjs-util@6.1.0
added 31 packages from 35 contributors and audited 165 packages in 6.096s
```

**Comment by MicahZoltu** [comment]
You may have me mixed up with someone else, I'm not recommending optional modules.  My recommendation is to swap the `keccak` dependency with `js-sha3` and swap the `secp256k1` dependency with `elliptic`.

If you believe that a performance change is worthy of a major version bump, then bump to v7 along with that change.  Personally, I don't think it is necessary to major version bump due to a potential/theoretic performance change in a library, but I would also not fight against a major version bump if others believe it is necessary.

**Comment by holgerd77** [comment]
@MicahZoltu @alcuadrado think your argumentation is pretty reasonable here, so we should consider replacing the respective dependencies.

@alcuadrado personally like the approach your proposing, @MicahZoltu what do you think? Any drawbacks here?

I would really like to have some numbers on performance first before we make further decisions, e.g. run the test suite of the VM with the alternative libraries injected.

**Comment by holgerd77** [comment]
@alcuadrado would it work with your approach to have a third party libraries using this library (e.g. the VM) default to the more performant version if it makes sense? Would you explicitly add the native implementation dependency in VM package.json?

**Comment by MicahZoltu** [comment]
Unfortunately `optionalDependencies` in NPM are still attempted to be installed, they just don't fail the entire install if they fail.  This means users will still run into error messages and long NPM install times due to NPM attempting to install `keccack` and `secp256k1` libraries, so I don't think it will address the problem fully.

This is documented at https://docs.npmjs.com/files/package.json#optionaldependencies
> [if] you would like npm to proceed if it cannot be found or fails to install, then you may put it in the optionalDependencies object.

**Comment by s1na** [comment]
Side note: using wasm modules for performance-sensitive functionality would also be an option (see [bitcoin-ts](https://github.com/bitauth/bitcoin-ts) or [rustbn.js](https://github.com/ethereumjs/rustbn.js) for examples).

**Comment by alcuadrado** [comment]
> @alcuadrado would it work with your approach to have a third party libraries using this library (e.g. the VM) default to the more performant version if it makes sense? Would you explicitly add the native implementation dependency in VM package.json?

I think that should be possible, but I'd let the final user choose.

> Unfortunately `optionalDependencies` in NPM are still attempted to be installed, they just don't fail the entire install if they fail. This means users will still run into error messages and long NPM install times due to NPM attempting to install `keccack` and `secp256k1` libraries, so I don't think it will address the problem fully.
> 
> This is documented at https://docs.npmjs.com/files/package.json#optionaldependencies
> 
> > [if] you would like npm to proceed if [the dependency] cannot be found or fails to install, then you may put it in the `optionalDependencies` object.

npm never stops surprising me in how bad it is :) I think this should be doable with `peerDependencies`, but it may be confusing. 

We could also not declare the dependency, but that can lead to version conflicts, unless we check them explicitly.

> Side note: using wasm modules for performance-sensitive functionality would also be an option (see [bitcoin-ts](https://github.com/bitauth/bitcoin-ts) or [rustbn.js](https://github.com/ethereumjs/rustbn.js) for examples).

I've been thinking about this for ages but never had the time to do it. The good thing about this other approach is that is super simple.

**Comment by s1na** [comment]
> The good thing about this other approach is that is super simple.

Yeah agree what you suggested is a really simple solution. I'll start a new thread to discuss feasibility of using wasm modules for the longer term future.

**Comment by fabioberger** [comment]
Also chiming in to say that I'd also love to see this switch in dependencies happen.

**Comment by holgerd77** [comment]
This has been fixed by the Nomic Labs-lead initiative to switch over to the [ethereum-cryptography](https://github.com/ethereum/js-ethereum-cryptography) package with various PRs for the different Util library versions like e.g. #259.

Will close here.
