### ISSUE TITLE
Throw error: field must have length * when I set allowZero but not allowLess

### ISSUE THREAD

**Issue by sc0Vu** [ethereumjs/ethereumjs-util#196]
Hi

I got this error:  field must have length *.
The option:
```JS
{
        name: 'z',
        length: 20,
        allowZero: true,
        default: new Buffer([]),
},
```

If I set z to `Buffer.from(0)`, it throw the error.

Should I set `allowLess` to true? 

Thanks!

**Comment by alcuadrado** [comment]
Hey @sc0Vu, I don't know how you got that, as `Buffer.from(0)` throws. 

Anyway, I suspect your problem is that you are confusing an empty Buffer with one with a single `00` byte.

**Comment by sc0Vu** [comment]
@alcuadrado Thanks! It's my misunderstood about allowZero, just close it.
