### ISSUE TITLE
EIP-1191: new address checksum algorithm

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-util#201]
[This EIP](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1191.md) introduces a new checksum algorithm, which adds the `chainId` to the checksum calculation.

This new checksum has already been implemented in web3.js, trezor, ledger, mycrypto, and myetherwallet. Some of them are already using it for RSK, as it was originally proposed as [RSKIP-60](https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP60.md).

We should probably implement it too. What do you think? @s1na @holgerd77 

This can be done in a backward compatible way as if no `chainId` is used, it defaults to EIP-55 checksums.

**Comment by holgerd77** [comment]
Seems to make sense, yes.

**Comment by holgerd77** [comment]
@alcuadrado Do you want to open a PR on this?
