### ISSUE TITLE
HD keys derivation

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-util#209]
I'm starting to think that this module is missing HD keys derivation (see: BIP32). I'm not completely if this functionality is a good fit for this, but wanted to open the discussion.

**Comment by holgerd77** [comment]
Isn't this included in https://github.com/ethereumjs/ethereumjs-wallet?

**Comment by alcuadrado** [comment]
Oh, yes, it does! It didn't occur to me to look there, as my understanding is that it is for creating and saving wallet files. I expected to find the low-level derivation function here.
