### ISSUE TITLE
Published toChecksumAddress function deviates from docs and TypeScript source

### ISSUE THREAD

**Issue by rekmarks** [ethereumjs/ethereumjs-util#218]
Per the `ethereumjs-util` [documentation](https://github.com/ethereumjs/ethereumjs-util/blob/master/docs/README.md#const-tochecksumaddress) and [source code](https://github.com/ethereumjs/ethereumjs-util/blob/master/src/account.ts#L42), the function signature of `toChecksumAddress` should be:
```ts
function(address: string, eip1191ChainId?: number): string
```

However, in the latest (`6.1.0`) NPM distribution, its signature is:
```js
toChecksumAddress: (address: string) => string;
```

The distribution's implementation follows this:
```js
exports.toChecksumAddress = function (address) {
    address = ethjsUtil.stripHexPrefix(address).toLowerCase();
    var hash = exports.keccak(address).toString('hex');
    var ret = '0x';
    for (var i = 0; i < address.length; i++) {
        if (parseInt(hash[i], 16) >= 8) {
            ret += address[i].toUpperCase();
        }
        else {
            ret += address[i];
        }
    }
    return ret;
};
```

Is the version with the optional `eip1191ChainId` parameter not supposed to be published yet?

**Comment by ryanio** [comment]
It looks like this was fixed with https://github.com/ethereumjs/ethereumjs-util/pull/204 in `6.2.0` 👍
