### ISSUE TITLE
Types not detected for ethjs-util re-exported methods

### ISSUE THREAD

**Issue by s1na** [ethereumjs/ethereumjs-util#219]
Here we're re-exporting methods of `ethjs-util`:

https://github.com/ethereumjs/ethereumjs-util/blob/3b1085059194b02354177d334f89cd82a5187883/src/index.ts#L2-L5

But because they're manually added to the `exports` object, typescript is not adding type definitions for them and Typescript users get an error when using one of those methods, e.g. `stripHexPrefix`.

**Comment by a1300** [comment]
Please assign this issue to me

**Comment by s1na** [comment]
Hi @a1300. Thanks for offering to help. I've assigned the issue to you.
