### ISSUE TITLE
Rename sha3 to keccak256

### ISSUE THREAD

**Issue by wanderer** [ethereumjs/ethereumjs-util#22]
https://github.com/ethereum/EIPs/issues/59

**Comment by ethers** [comment]
Solidity added `keccak256`.  Reconsider the rename? https://github.com/ethereum/EIPs/issues/59#issuecomment-246123157

**Comment by axic** [comment]
It can be added as an alias now and the old `sha3` be removed at the next major bump.

**Comment by axic** [comment]
I think adding it as an alias should be done ASAP and then retiring `sha3` in the next breaking release.
