### ISSUE TITLE
Split tests from index.js into separate files

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-util#229]
Test cases in this libraries are all packed into one big `test/index.js` file. This makes it hard to work with the tests.

Tests should be broken to separate files analog to the module structure in the [src folder](https://github.com/ethereumjs/ethereumjs-util/tree/master/src) to make it easier to work on specific functionality and have an overview on functionality coverage.

Would be nice to have this for continued work on #228, no strict precondition though (of course).

**Comment by ryanio** [comment]
Thanks for the issue, I’ll work on this today.

**Comment by evertonfraga** [comment]
This is a good opportunity to migrate the test runner to `ts-node` as well.

**Comment by ryanio** [comment]
> This is a good opportunity to migrate the test runner to `ts-node` as well.

Sure great I can include that.
