### ISSUE TITLE
Build fails on OSX El Capitan

### ISSUE THREAD

**Issue by MaiaVictor** [ethereumjs/ethereumjs-util#24]
$ npm install ethereumjs-util

    > sha3@1.2.0 install /Users/v/Crypto/btc/node_modules/ethereumjs-util/node_modules/keccakjs/node_modules/sha3
    > node-gyp rebuild

    CXX(target) Release/obj.target/sha3/src/addon.o
    CXX(target) Release/obj.target/sha3/src/displayIntermediateValues.o
    CXX(target) Release/obj.target/sha3/src/KeccakF-1600-reference.o
    CXX(target) Release/obj.target/sha3/src/KeccakNISTInterface.o
    CXX(target) Release/obj.target/sha3/src/KeccakSponge.o
    SOLINK_MODULE(target) Release/sha3.node
    ld: library not found for -lgcc_s.10.5
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [Release/sha3.node] Error 1
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Darwin 15.0.0
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/v/Crypto/btc/node_modules/ethereumjs-util/node_modules/keccakjs/node_modules/sha3
    gyp ERR! node -v v4.1.0
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok

    > secp256k1@3.0.0 install /Users/v/Crypto/btc/node_modules/ethereumjs-util/node_modules/secp256k1
    > npm run rebuild

    > secp256k1@3.0.0 rebuild /Users/v/Crypto/btc/node_modules/ethereumjs-util/node_modules/secp256k1
    > node-gyp rebuild

    CXX(target) Release/obj.target/secp256k1/src/addon.o
    CXX(target) Release/obj.target/secp256k1/src/privatekey.o
    CXX(target) Release/obj.target/secp256k1/src/publickey.o
    CXX(target) Release/obj.target/secp256k1/src/signature.o
    CXX(target) Release/obj.target/secp256k1/src/ecdsa.o
    CXX(target) Release/obj.target/secp256k1/src/ecdh.o
    CC(target) Release/obj.target/secp256k1/src/secp256k1-src/src/secp256k1.o
    In file included from ../src/secp256k1-src/src/secp256k1.c:13:
    In file included from ../src/secp256k1-src/src/field_impl.h:19:
    ../src/secp256k1-src/src/field_5x52_impl.h:54:13: warning: unused function 'secp256k1_fe_verify' [-Wunused-function]
    static void secp256k1_fe_verify(const secp256k1_fe *a) {
                ^
    In file included from ../src/secp256k1-src/src/secp256k1.c:15:
    ../src/secp256k1-src/src/group_impl.h:219:12: warning: unused function 'secp256k1_gej_is_valid_var' [-Wunused-function]
    static int secp256k1_gej_is_valid_var(const secp256k1_gej *a) {
            ^
    2 warnings generated.
    CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_privatekey_parsing.o
    SOLINK_MODULE(target) Release/secp256k1.node
    npm ERR! Darwin 15.0.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "ethereumjs-util"
    npm ERR! node v4.1.0
    npm ERR! npm  v2.14.3
    npm ERR! code ELIFECYCLE

    npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the sha3@1.2.0 install script 'node-gyp rebuild'.
    npm ERR! This is most likely a problem with the sha3 package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls sha3
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/v/Crypto/btc/npm-debug.log

**Comment by wanderer** [comment]
hi @MaiaVictor it looks like [sha3](https://github.com/phusion/node-sha3) is failing to build. Can you try building sha3 by itself? Lets see if it still fails then

**Comment by axic** [comment]
btw I am using El Capitan myself and it works here. I have latest xcode and node.

**Comment by axic** [comment]
@MaiaVictor closing, please reopen if it persists
