### ISSUE TITLE
Browser compatible elliptic alternative to secp256k1

### ISSUE THREAD

**Issue by justinkook** [ethereumjs/ethereumjs-util#240]
The upgrade to `web3: 1.2.4+` has added `ethereumjs-tx -> ethereumjs-util` package as a dependency to `web3-eth-accounts`.

<img width="1000" alt="Screen Shot 2020-02-25 at 12 32 12 PM" src="https://user-images.githubusercontent.com/23103037/75273287-5b9b3800-57ce-11ea-89da-ab4d5a5f5b3a.png">

Are there any plans to introduce a switcher based on node or browser to be able to use web3 in the browser / webview based apps?

Rough example:
```
if (browser) {
   var EC = require('elliptic').ec;
   secp256k1 = new EC('secp256k1');
} else { 
   secp256k1 = require('secp256k1');
}
```

**Comment by cgewecke** [comment]
Hi @justinkook  Are you certain secp256k1 is the cause of the error you're seeing?

In [bitpay/bitcore 2736][1] you say:
> secp256k1 is node only package

...but sepc256k1 already falls back on elliptic in the browser (see their [README][2]).

Additionally, Web3 runs [some unit tests][3] that use ethereumjs-tx in a headless browser after bundling with browserify without problems. 

[1]: https://github.com/bitpay/bitcore/pull/2736
[2]: https://github.com/cryptocoinjs/secp256k1-node#secp256k1-node
[3]: https://travis-ci.org/ethereum/web3.js/jobs/654854322#L565-L649

**Comment by cgewecke** [comment]
@justinkook Closing due to lack of response, please just ping if you have more info about this.
