### ISSUE TITLE
Buffer error with keccak256 related to abi.encodePacked

### ISSUE THREAD

**Issue by naszam** [ethereumjs/ethereumjs-util#254]
Hi, 

I've encountered an issue with the latest version of ethereumjs-util (v7.0.2) posted on [OpenZeppelin Forum](https://forum.openzeppelin.com/t/merkleproof-sol-claim-error-vm-exception-while-processing-transaction/2918).
It seems to work with ethereumjs-util v6.2

Thanks!

**Comment by holgerd77** [comment]
//cc @ryanio @cgewecke

**Comment by ryanio** [comment]
hey @naszam, thanks for sharing. could you let us know exactly what error you are encountering, and a minimal case to reproduce the issue?

**Comment by cgewecke** [comment]
@naszam Read the OZ thread and I see that the maintainer responding to your question says

> I had to use the v6.2 release of ethereumjs-util rather than the v7 as I was getting errors that I didn’t explore 

.. and then links to [the release notes][1].

[1]: `https://github.com/ethereumjs/ethereumjs-util/releases/tag/v7.0.0

Do you have an example stack-trace for the error? 

In v7, the methods are type-strict - it's possible you just need to input parameters with the correct data type for the method you're calling. For example, `keccak256` now requires a buffer input by default. And there are  convenience methods like `keccakFromString` that will hash a string.

**Comment by naszam** [comment]
This is a repo I've created to reproduce the issue:

https://github.com/naszam/oz-merkle-support

**Comment by cgewecke** [comment]
@naszam 
+ cloned https://github.com/naszam/oz-merkle-support
+ `npm i`
+ launched ganache-cli separately 
+ `npx truffle test` 
```
Error: Could not find @openzeppelin/contracts/cryptography/MerkleProof.sol from any sources; imported from /Users/cgewecke/code/oz-merkle-support/contracts/MyContract.sol
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-resolver/index.js:76:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/async/internal/onlyOnce.js:12:1
    at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/async/whilst.js:68:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-resolver/index.js:64:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-resolver/fs.js:85:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/async/internal/once.js:12:1
    at replenish (/usr/local/lib/node_modules/truffle/build/webpack:/~/async/internal/eachOfLimit.js:61:1)
    at iterateeCallback (/usr/local/lib/node_modules/truffle/build/webpack:/~/async/internal/eachOfLimit.js:50:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/async/internal/onlyOnce.js:12:1
    at ReadFileContext.callback (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-resolver/fs.js:81:1)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:256:13)
```

Would be helpful if you could show an error stack trace referencing ethereumjs-util in this issue and indicate which part of your reproduction case triggers it.

**Comment by naszam** [comment]
Sorry OpenZeppelin wasn't included.
Just committed!

**Comment by alcuadrado** [comment]
This issue caught my attention, as I thought that maybe the new `keccack` version was broken.

The problem comes from using `keccakFromString` here: https://github.com/naszam/oz-merkle-support/blob/master/test/merkleTree.js

That function is intended to hash utf8 encoded strings. What you want to do is transform hex encoded data into buffers, and then hash that. `keccak(toBuffer(data))` would do it.

I tried this change in your repo and it fixed it.

**Comment by naszam** [comment]
Thanks!
But I guess it needs to be fixed on ethereumjs-util as well.
