### ISSUE TITLE
Crashes on node:12-alpine

### ISSUE THREAD

**Issue by chaitanyapotti** [ethereumjs/ethereumjs-util#255]
Process exits on node with alpine.
Sample docker file

```
FROM node:12-alpine

WORKDIR /app

COPY package*.json ./

ENV NODE_OPTIONS --max-old-space-size=4096

RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
        && npm ci && apk del .gyp

COPY . .

EXPOSE 2020

CMD npm start
```

I might be missing some alpine dependency though!

**Comment by alcuadrado** [comment]
Hey @chaitanyapotti,

This doesn't look related to this project at all. Can you confirm that it is and give the necessary steps to reproduce it?

**Comment by chaitanyapotti** [comment]
after further testing, the issue seems to be present when i use v7 of ethereumjs-util with v2 of eth-sig-util. I get a `segmentation fault(core dumped)`.
But, when i use the library standalone, i don't face any issues. Not sure why this is occuring but looks to be not a problem with this package

**Comment by holgerd77** [comment]
@chaitanyapotti thanks for the update on this! 👍
