### ISSUE TITLE
Why add 27 to ecsign?

### ISSUE THREAD

**Issue by MrChico** [ethereumjs/ethereumjs-util#26]
Hey, why do you add 27 to v in ecsign, and subtract it again in ecrecover?
I compared the values returned by ecsign with the web3.eth.sign of the go client and they seem to return a v that does not have 27 added to it.
In other words, to recover a public key using the output of geths web3.eth.sign I need to subtract 27 from v to use ethereumjs-util.recover. 

What is the reason for this?

**Comment by wanderer** [comment]
> What is the reason for this?

I'm not sure.. But its specified that way in the yellow paper. And the to generate the correct transaction hash we need to store the v that way.

**Comment by MrChico** [comment]
You are right. I will ask the go team why they do it the other way

**Comment by MrChico** [comment]
They have acknowledged it as being faulty:
https://github.com/ethereum/go-ethereum/issues/2053
