### ISSUE TITLE
[bug] hash.ts not work on alpine linux image

### ISSUE THREAD

**Issue by wanseob** [ethereumjs/ethereumjs-util#266]
https://github.com/ethereumjs/ethereumjs-util/blob/c6e8f3e05eecb3df2e1435faf6a1fdd4b87932ef/src/hash.ts#L13-L32

keccak does not work on alpine linux image.
Found this bug when I use docker node:12-alpine image.

**Comment by wanseob** [comment]
https://github.com/ethereum/js-ethereum-cryptography/issues/3
https://github.com/cryptocoinjs/keccak/issues/15
https://github.com/ethereumjs/ethereumjs-vm/issues/817

**Comment by alcuadrado** [comment]
Closing this issue as it was followed and fixed in https://github.com/cryptocoinjs/keccak/issues/15
