### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by shark0der** [ethereumjs/ethereumjs-util#282]
I've was using `web3.utils.sha3` for `CREATE2` salt bruteforce which was very slow and was hinted by @alcuadrado to try `ethereumjs-util` instead. I've ported the script and it runs indeed much much faster however it has a huge memory leak as it continuously eats up available RAM until the OS runs out of it. On my laptop it consumed around 2GB in one minute and immediatelly freed it up when killed.

The current script is available at this address: https://github.com/NexusMutual/smart-contracts/blob/a80f1c0e85da24aba7e0213846727e0241e6ec77/scripts/deploy-with-create2.js

Usage:
```
git checkout a80f1c0e85da24aba7e0213846727e0241e6ec77
npm i
export MAINNET_FACTORY_ADDRESS=0x7B4e2b0CD6DfeAd61600647B3958199867277Ec2
export HARDHAT_NETWORK=mainnet
export TARGET_CONTRACT=ClaimsReward
node scripts/deploy-with-create2.js find 0x123
```

It will compile the contracts automatically.

**Comment by jochem-brouwer** [comment]
Hi and thanks for opening this issue! This should be caused by `keccak256` per your script, right? If I run `keccak256` in a while loop then I do not get a memory leak, node memory stays stable. Are you sure this problem is not caused by some artifact in your script?

**Comment by holgerd77** [comment]
No follow-up, will close.
