### ISSUE TITLE
bnToRlp: misleading name

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-util#284]
`bnToRlp` implies (to me) that we convert a BN to a Buffer, and then `rlp.encode` it, and return that value. However, that is not the case: we convert it to a Buffer and then strip the leading zeros.

Is there actually any case where any zeros are stripped? Why should BN create a Buffer with leading zero bytes?

**Comment by ryanio** [comment]
I created this method as a helper when working on the tx library in the monorepo to prepare buffers to be rlp encoded.

Perhaps the name isn't the greatest (better name for it could be `bnToUnpaddedBuffer`), but it's used e.g. [here]( https://github.com/ethereumjs/ethereumjs-monorepo/blob/6822c084d8b9d3f97e35ae546a766fcc36547545/packages/tx/src/transaction.ts#L321) and could be used to replace [this](https://github.com/ethereumjs/ethereumjs-monorepo/blame/6822c084d8b9d3f97e35ae546a766fcc36547545/packages/block/src/header.ts#L553):

```typescript
unpadBuffer(toBuffer(this.difficulty)), // we unpadBuffer, because toBuffer(new BN(0)) == <Buffer 00>
```
