### ISSUE TITLE
Split off the crypto functions

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-util#35]
See https://github.com/ethereumjs/ethereumjs-util/pull/34#issuecomment-211394212

**Comment by kumavis** [comment]
+1 👍 👍 👍 👍

**Comment by kumavis** [comment]
A large number of modules just pull in ethereumhs-util for the hex/buffer/BN/int conversion

**Comment by alcuadrado** [comment]
I'd say this issue can be closed. This library has already been split into multiple files.

**Comment by holgerd77** [comment]
Thanks, will close, addressed in #182.
