### ISSUE TITLE
Serialize message signatures

### ISSUE THREAD

**Issue by kumavis** [ethereumjs/ethereumjs-util#36]
they come out in this format:
```js
function concatSig(v, r, s) {
  r = ethUtil.fromSigned(r)
  s = ethUtil.fromSigned(s)
  v = ethUtil.bufferToInt(v)
  r = ethUtil.toUnsigned(r).toString('hex')
  s = ethUtil.toUnsigned(s).toString('hex')
  v = ethUtil.stripHexPrefix(ethUtil.intToHex(v))
  return ethUtil.addHexPrefix(r.concat(s, v).toString("hex"))
}
```

**Comment by axic** [comment]
@fanatid are `r` and `s` in two's complement format in `secp256k1.sign()`?

@kumavis I don't think the above should need to fromSigned/toUnsigned conversion. Also it converts it to the format the new `geth` is using (the one uses `v-27`).

**Comment by kumavis** [comment]
this is just copy pasta from lightwallet https://github.com/ConsenSys/eth-lightwallet/blob/master/lib/signing.js
sorry im not very familiar with this one

**Comment by kumavis** [comment]
obv we should include a verify method

**Comment by fanatid** [comment]
@axic `secp256k1.sign` return `r`/`s` as unsigned numbers that lower than `n` (FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141)
