### ISSUE TITLE
npm install error windows - cannot open input file 'C:\OpenSSL-Win64\lib\libeay 32.lib

### ISSUE THREAD

**Issue by nitinsurana** [ethereumjs/ethereumjs-util#43]
```
LINK : fatal error LNK1181: cannot open input file 'C:\OpenSSL-Win64\lib\libeay32.lib' [C:\project\etherwallet\node_mod
ules\secp256k1\build\secp256k1.vcxproj]
```

Probably, resolution can be found in the following link :
https://github.com/blockapps/blockapps-js/issues/33

**Comment by wanderer** [comment]
Please move to [secp256k1](https://github.com/cryptocoinjs/secp256k1-node)

**Comment by bellaj** [comment]
just install the openssl from here http://slproweb.com/download/

**Comment by fanatid** [comment]
@nitinsurana please check windows instruction for secp256k1-node: https://github.com/cryptocoinjs/secp256k1-node/tree/15e14632eabfa54248af97f3ff7a9dcf96f67271#windows

**Comment by halinh12310** [comment]
@nitinsurana you can down lib from [here](https://github.com/ReadyTalk/win32/blob/master/msvc/lib/libeay32.lib) and copy to `C:\OpenSSL-Win32\lib` folder.
P/s: Sorry for my bad english. So I Hope this helps you

**Comment by lporras** [comment]
@halinh12310 That worked for me thanks!

**Comment by nirdil** [comment]
install the following OpenSSL https://slproweb.com/download/Win64OpenSSL-1_0_2n.exe
version 1.1.0 won't work as they changed the lib names

**Comment by riyazpanarwala** [comment]
Thanks @halinh12310 . 
Added libeay32.lib in c:\OpenSSL-win64\lib folder
and it works for me.

**Comment by unicornist** [comment]
Just install latest (but below 1.1) version of Windows installer for OpenSSL.
Old links posted here are broken. This is now the download page of the official website: http://slproweb.com/products/Win32OpenSSL.html

**Comment by A1M918** [comment]
> 
> 
> @nitinsurana you can down lib from [here](https://github.com/ReadyTalk/win32/blob/master/msvc/lib/libeay32.lib) and copy to `C:\OpenSSL-Win32\lib` folder.
> P/s: Sorry for my bad english. But I Hope this helps you

worked for me. Thanks.

**Comment by Kerinlin** [comment]
> @nitinsurana you can down lib from [here](https://github.com/ReadyTalk/win32/blob/master/msvc/lib/libeay32.lib) and copy to `C:\OpenSSL-Win32\lib` folder.
> P/s: Sorry for my bad english. But I Hope this helps you
It works for me.Thanks!
