### ISSUE TITLE
Feature - eth_sign signature method (different from tx sig)

### ISSUE THREAD

**Issue by kumavis** [ethereumjs/ethereumjs-util#45]
Continued from https://github.com/ethereumjs/ethereumjs-util/pull/44

Ethereum signs messages (via eth_sign rpc) and transactions using a different format. We should provide a utility function for both formats.

**Comment by wanderer** [comment]
i guess we could add a option to `ecsign/verify`

**Comment by axic** [comment]
Isn't #42 solving this?

**Comment by kumavis** [comment]
Resolved by #42 thanks @axic

**Comment by kumavis** [comment]
After all this, geth is intending to change its behavior
ethereum/go-ethereum#2053
