### ISSUE TITLE
ecrecover doesn't recover correct address if there are leading zeros

### ISSUE THREAD

**Issue by Georgi87** [ethereumjs/ethereumjs-util#48]
Assuming the following message and signature created with given address:

```
msg = 'a4d15d21565d48b67f250b98d2b0a16ee08b7b5b17d88b96e0459cf0a5366c98'
sgn = '00c78fb446754b98694294cd4b64a9d706eb6329fa42994a1f3bcd660c2cc6ef45238a54feaac4d54b217b9c32448d208635e8b2cf007aff7ad7fe20036e9e6f1b'

address = '4cd548342a562d9e47344394a62a25c8de8e8e46'
```

Following recovery code produces wrong address (`8291d6c76377ee2ad35a7997e41397914e575f3d` instead of `4cd548342a562d9e47344394a62a25c8de8e8e46`)

```
var r = EthJS.Util.toBuffer('0x' + sgn.slice(0,64));
var s = EthJS.Util.toBuffer('0x' + sgn.slice(64, 128));
var v = EthJS.Util.toBuffer('0x' + sgn.slice(128, 130));
var m = EthJS.Util.toBuffer('0x' + msg);
var pub = EthJS.Util.ecrecover(m, v, r, s);
EthJS.Util.pubToAddress(pub).toString('hex') == '8291d6c76377ee2ad35a7997e41397914e575f3d';
```

However, the code works for all other cases only signatures starting with 0 fail. That's why I assume that there is a bug in `ecrecover`.

**Comment by axic** [comment]
I would suggest using the `fromRpcSig()` method to split up the signature into v/r/s components.

@Georgi87 can you tell me which tool have you used to create that signature?

**Comment by fanatid** [comment]
@axic given data are valid:
```
msg = a4d15d21565d48b67f250b98d2b0a16ee08b7b5b17d88b96e0459cf0a5366c98
signature = 00c78fb446754b98694294cd4b64a9d706eb6329fa42994a1f3bcd660c2cc6ef45238a54feaac4d54b217b9c32448d208635e8b2cf007aff7ad7fe20036e9e6f1b
produce address = 8291d6c76377ee2ad35a7997e41397914e575f3d
```

@Georgi87 private key for this address is secret? With given private key would be much easier understand whats wrong here, sign/recover/pubToAddress. If private key is secret can you provide public key for `4cd548342a562d9e47344394a62a25c8de8e8e46` at least?

**Comment by axic** [comment]
@Georgi87 please reopen if it still persists

**Comment by isysd-mirror** [comment]
This may be a chainid issue. Different chainids will yield different addresses, and [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) changed this behavior relatively recently.
