### ISSUE TITLE
Use Typeforce for type checking

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-util#51]
See https://www.npmjs.com/package/typeforce

**Comment by holgerd77** [comment]
The library still has only 18 stars on GitHub, this seems to not have been established enough and probably TypeScript will me the more solid/standardized solution with efforts only in progress.

Will close this.

**Comment by fanatid** [comment]
This is different things, if I understand TS correctly (never used it).
`typeforce` from @dcousens working in runtime and no need any source code transformation
