### ISSUE TITLE
Installation problem with sha3 Debian node v4.6 

### ISSUE THREAD

**Issue by diego-G** [ethereumjs/ethereumjs-util#52]
The dependency is not working. I got an error when installingit. 
https://github.com/ethereumjs/ethereumjs-abi/issues/31
https://github.com/phusion/node-sha3/issues/27

**Comment by diego-G** [comment]
Anyone it's working on this?

**Comment by fanatid** [comment]
@diego-G I think you should start from providing maximum information. Debian and node v4.6 says absolutely nothing.

**Comment by diego-G** [comment]
Resolved: sudo apt-get install build-essential
