### ISSUE TITLE
isValidAddress wrong behaviour?

### ISSUE THREAD

**Issue by fanatid** [ethereumjs/ethereumjs-util#54]
Why [isValidAddress](https://github.com/ethereumjs/ethereumjs-util/blob/9453f87827a1eb019538000851ff149b13229805/index.js#L467) not checked checksum if address has upper and lower symbols at one time?

**Comment by fanatid** [comment]
ping :)

**Comment by wanderer** [comment]
pinging @axic :D

**Comment by fanatid** [comment]
@wanderer what you thoughts about `isValidAddress`? Should it check only length/symbols or also check checksum if address has upper/lower symbols?

**Comment by axic** [comment]
There's also `isValidChecksumAddress`.

**Comment by fanatid** [comment]
Yes and even more, `isValidChecksumAddress` was added before `isValidAddress` IIRC.
but when you call `isValidAddress` you expect that it checks checksum also, isn't it?

**Comment by axic** [comment]
No, I would keep `isValidAddress` which checks the validity according to the yellow paper. *EIP55* is not even "accepted" yet (what `isValidChecksumAddress` implements).

**Comment by fanatid** [comment]
for example -- `0xD35e6f3b26f8992a7f023ad878e13a82dded2232`
`isValidAddress` return `true`, but it is not valid

**Comment by axic** [comment]
If it is 40 hex digits then it is a valid address.

**Comment by fanatid** [comment]
Thanks for explanation.
Can you give link to EIP55?

**Comment by axic** [comment]
https://github.com/ethereum/EIPs/issues/55

Nevertheless we could improve this. Some ideas:
- `isValidChecksumAddress` to accept all lowercase without checking the checksum (against EIP55)
- add an option (default false) to `isValidAddress` which checks the checksum if it is mixed case

I'm not fully convined by any of these. Have better ideas?

**Comment by fanatid** [comment]
option argument fine for me, if you want I can create PR

**Comment by fanatid** [comment]
Thank you for the link btw, I googled it, but not think that EIP is discussion thread on github :laughing:
