### ISSUE TITLE
fromRpcSig and toRpcSig should have an option to include the `geth header`

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-util#63]
> "\x19Ethereum Signed Message:\n" + len(message).

For more see https://github.com/ethereum/go-ethereum/pull/2940.

(From #60.)

**Comment by Neurone** [comment]
I think this issue can be closed: since the merge of https://github.com/ethereumjs/ethereumjs-util/pull/67 it seems to me there's no more reason to modify `fromRpcSig` and `toRpcSig`.

**Comment by Neurone** [comment]
@holgerd77 No, it does not. The `Geth` header is added to the payload before signing it: `hashPersonalMessage` already does exactly that.
