### ISSUE TITLE
How to run browserify so it run in a browser? What global object it creates?

### ISSUE THREAD

**Issue by stefek99** [ethereumjs/ethereumjs-util#77]
I got https://github.com/substack/node-browserify installed.

Cloned the repo.

`browserify index.js -o browserified.js`

```
<!doctype html>
<html>
  <head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src='http://ajax.googleapis.com/ajax/libs/angularjs/1.2.28/angular.min.js'></script>
    <script src='browserified.js'></script>
    <script>
      var app = angular.module("app", []);

      app.controller("ctrl", function($scope) {
        $scope.message = "It works!";
      });

    </script>
  </head>
  <body ng-app="app" ng-controller="ctrl">
    {{ message }}

  </body>
</html>
```

When I use version from CDN it works: https://wzrd.in/standalone/ethereumjs-util@latest

> console.log(ethereumjsUtil);

> It's probably just under a different global

--

SO chat: http://chat.stackoverflow.com/transcript/message/36767135#36767135

JS Fiddle with CDN: https://jsfiddle.net/ztqeLmmk/

**Comment by fanatid** [comment]
You should pass `--standalone` option to browserify.

from [wzrd.in](https://wzrd.in/):
```
GET /standalone/:module
GET /standalone/:module@:version
In this case, --standalone is passed to browserify.
```
