### ISSUE TITLE
Install  ethereumjs-util on Raspberry Pi

### ISSUE THREAD

**Issue by johnshearing** [ethereumjs/ethereumjs-util#81]
I am using a raspberry pi as an air-gapped computer. Web3 installs and works just fine on my pi. My problem is I need to get a public address from a private key and this requires ethereumjs-util which will not install on my raspberry pi. I am using a pi 2 with raspbian. The error log can be found at the following link

https://ethereum.stackexchange.com/questions/18395/npm-install-ethereumjs-util-on-a-raspberry-pi

Can someone please tell me what I need to do in order to install ethereumjs-util on a pi. Thanks, John
johnshearing@gmail.com

**Comment by Silur** [comment]
I see this is already solved on your stackexchange so I guess there's no obligations to close

**Comment by johnshearing** [comment]
Sorry, Bad manners. I should have closed this issue.  I am still learning about how to use github. Hope to be a better citizen in the future. :)
