### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by Joeblockmark** [ethereumjs/ethereumjs-util#82]
When I try to import ethereumjs-util I get the error Uncaught ReferenceError: Buffer is not defined

**Comment by Joeblockmark** [comment]
Never mind this is apparently a deliberate change in [meteor 1.5](https://github.com/meteor/meteor/issues/8645) It can be fixed by adding `global.Buffer = global.Buffer || require("buffer").Buffer;` to the code. I won't delete this incase anyone makes the same mistake.

**Comment by fanatid** [comment]
@Joeblockmark should work now without hack
