### ISSUE TITLE
`.` in filename of v3 keystore files

### ISSUE THREAD

**Issue by tayvano** [ethereumjs/ethereumjs-util#83]
Anyone know if this has a purpose? I would like to remove it to address some user experience issues that are causing confusion on certain OS's, but want to ensure there wasn't a reason the file has a bizarre extension.

e.g. 

`UTC--2017-07-09T17-19-47.572Z--a4789ca05f7094186b1d1eb387d08856039d6284` 

would be

`UTC--2017-07-09T17-19-47572Z--a4789ca05f7094186b1d1eb387d08856039d6284`

**Comment by fanatid** [comment]
OOI, where I can read about keystore format?
As I see parity@1.7.0 uses seconds without milliseconds https://github.com/paritytech/parity/blob/v1.7.0/ethstore/src/dir/disk.rs#L201-L202

**Comment by axic** [comment]
I think this is on the wrong repo as the function is in ethereumjs-wallet.

There is no spec for this, it is just a timestamp. I think it is a good idea not having dots in it.

**Comment by tayvano** [comment]
@axic Derp. Thanks for the info. When / if we update the filename, I'll ping you or PR in ethereumjs-wallet.
