### ISSUE TITLE
"defineProperties" may have a problem detecting zero-value Buffers that are converted from a hex-encoded string containing a quantity of `0` characters not exactly equal to 2

### ISSUE THREAD

**Issue by warren-bank** [ethereumjs/ethereumjs-util#85]
* the function: [defineProperties()](https://github.com/ethereumjs/ethereumjs-util/blob/v5.1.2/index.js#L573)
* contains the [code](https://github.com/ethereumjs/ethereumjs-util/blob/v5.1.2/index.js#L601):

```javascript
if (v.toString('hex') === '00' && !field.allowZero) {
  v = Buffer.allocUnsafe(0)
}
```

* please correct me if I'm wrong, but I believe that:
  * for an ethereum address that was entered as a hex-encoded string:<br>
    `"0x0000000000000000000000000000000000000000"`
  * `v.toString('hex')` will equal `"0000000000000000000000000000000000000000"`<br>
    which doesn't pass this conditional test

* should this check be rewritten in a more general way? ex:

```javascript
if (v.toString('hex').match(/^0+$/) !== null && !field.allowZero) {
  v = Buffer.allocUnsafe(0)
}
```

**Comment by warren-bank** [comment]
verified..

__test script__:

```javascript
#!/usr/bin/env node

const ethUtil = require('ethereumjs-util')

let v = ethUtil.toBuffer('0x0000000000000000000000000000000000000000')

v = v.toString('hex')
console.log(v)
console.log(v === '00')
console.log(v.match(/^0+$/) !== null)
```

__output___:

```text
0000000000000000000000000000000000000000
false
true
```

**Comment by Silur** [comment]
included in https://github.com/ethereumjs/ethereumjs-util/commit/83554fa05047c36cfe9dcac6404d99a5048cba28, thanks for your input

**Comment by Silur** [comment]
@warren-bank  so it turns out that this check is the desired behavior, and my commit broke some upstream libraries, master is reset
