### ISSUE TITLE
Inconsistent between `isValidAddress` and `defineProperties`

### ISSUE THREAD

**Issue by tranvictor** [ethereumjs/ethereumjs-util#89]
In `isValidAddress`:
```
exports.isValidAddress = function (address) {
  return /^0x[0-9a-fA-F]{40}$/i.test(address)
}
```
We accept a string starting with `0X` because the regex is with `i` case insensitive flag. However `0X` is invalid hex string to `defineProperties`.

I do not think we should consider `0X` a valid prefix of a hex string.

Proposal: Just remove `i` flag in the regex. I don't see any good reasons to have it here.

**Comment by axic** [comment]
I think you are right. It must have been a mistake, since the regex contains both upper/lowercase.

Could you open a pull request fixing it?

**Comment by tranvictor** [comment]
@axic sure, i will propose a PR soon.
