### ISSUE TITLE
 exports.intToBuffer() doesn't exist

### ISSUE THREAD

**Issue by vrolland** [ethereumjs/ethereumjs-util#93]
the function :  exports.intToBuffer() called in exports.toBuffer doesn't exist

**Comment by holgerd77** [comment]
This is included in ``ethjs-util``, https://github.com/ethjs/ethjs-util/blob/master/src/index.js#L52, 
please test such stuff with node before filing an issue.

**Comment by vrolland** [comment]
my bad.

**Comment by holgerd77** [comment]
No problem. :-)
