### ISSUE TITLE
republish to npm without babel deps (5.1.2 pulls in babel-preset-es2015 and babelify)

### ISSUE THREAD

**Issue by mvayngrib** [ethereumjs/ethereumjs-util#94]
thanks!

**Comment by holgerd77** [comment]
You are not honestly expecting that your issue will ever be considered without any explanation or context, or do you?

**Comment by mvayngrib** [comment]
oh, i thought i explained in the title

package.json for the published version 5.1.2 has babel-preset-es2015 and babelify in dependencies (recently moved to devDependencies where it belongs). That means anyone installing 5.1.2 is pulling in those heavy deps for no reason (they are build tools). I was hoping you could republish 5.1.3 now that they've been moved to devDependencies

**Comment by holgerd77** [comment]
Ah ok, thanks!

I'm not the main contributor to this library and I'm not sure about the latest commits, is this finished/coherent work? @wanderer @Silur ?

**Comment by Silur** [comment]
there was an effort to port all ethjs repos without babel dependencies but @kumavis pointed out that it would break some upstream stuff, I wonder what is the situation now maybe @cdetrio or @kumavis can give greenlight to further work on this

**Comment by kenshyx** [comment]
This is a real issue right now because `babel-preset-es2015` is deprecated.

**Comment by holgerd77** [comment]
Just published v5.1.3 https://github.com/ethereumjs/ethereumjs-util/releases/tag/v5.1.3 with the latest changes from `master`, @kenshyx I also switched to the `babel-preset-env` preset.
