### ISSUE TITLE
Function to check if the address is a Zero Address

### ISSUE THREAD

**Issue by subramanianv** [ethereumjs/ethereumjs-util#95]
There must be a function to check if a given address is a Zero Address (0x0000000000000000000000000000000000000000)

**Comment by holgerd77** [comment]
Can you give an example use case for this and shortly describe why you think this is important/missing?

**Comment by subramanianv** [comment]
When you query a smart contract function that returns an address. If the address that it returns is not set, then it returns a NULL Address. TestRPC returns 0x0000000000000000000000000000000000000000. Mainnet returns 0x. A utility function to test for a null address would be handy

**Comment by holgerd77** [comment]
Ok, thanks.

**Comment by subramanianv** [comment]
@holgerd77  Can I send a PR ? Or is there a gitter channel where I need to post this ?

**Comment by holgerd77** [comment]
@subramanianv No, feel free to submit a PR. @axic @cdetrio Can you cross-check if this is a useful addition, and intervene if you think there are reasons not to add this?

**Comment by subramanianv** [comment]
@axic @cdetrio @holgerd77 Please review the PR #99

**Comment by subramanianv** [comment]
@holgerd77 Here is the new PR from my own branch #100. I have also made the requested changes
